### ISSUE TITLE
Problem with bug ceph

### ISSUE THREAD

**Issue by KVInventoR** [thelan/ceph-zabbix#9]
Ceph return: 
Received value [libust[25295/25295]: Warning: HOME environment variable not set. Disabling LTTng-UST per-user tracing. (in setup

this event discribed here:
http://forum.proxmox.com/threads/24031-Proxmox4-and-ceph

all elements in Templace_Ceph_Cluster 
return: Received value [libust[25295/25295]: Warning: HOME environment variable not set. Disabling LTTng-UST per-user tracing. (in setup

Could you fix this problem in script: ceph-status.sh
Maybi need append filter and ignore this text message in variables which return ceph.

**Comment by thelan** [comment]
Hello,

When calling a script via zabbix agent it seems now it seems.
You can both declare the HOME variable on the begining of the bash script.
or preprend the HOME variable on each line on the zabbix agent configuration parameters.
